# Generated by Django 4.0.4 on 2022-11-12 00:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipts', '0001_initial'),
        ('customers', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('shop', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='customers.customers')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedback', to='receipts.receipt')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='vendors.vendor')),
            ],
        ),
    ]
