# Generated by Django 4.0.4 on 2022-07-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='ready',
        ),
    ]
