# Generated by Django 4.0.4 on 2022-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
