# Generated by Django 4.0.4 on 2022-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a customer. ', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='external_vendor',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a external vendor. ', verbose_name='external vendor'),
        ),
        migrations.AddField(
            model_name='user',
            name='sasapay_vendor',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a sasapay vendor. ', verbose_name='sasapay vendor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
