# Generated by Django 4.0.4 on 2022-11-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sasapay', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
    ]
