# Generated by Django 4.0.4 on 2022-11-01 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sasapay', '0002_delete_transactiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TransactionType', models.CharField(max_length=255)),
                ('TransactionDate', models.DateTimeField()),
                ('MerchantRequestID', models.CharField(max_length=255)),
                ('CheckoutId', models.CharField(max_length=255)),
                ('TransactionAmount', models.IntegerField()),
                ('Paid', models.BooleanField()),
                ('AmountPaid', models.IntegerField()),
                ('PaidDate', models.DateTimeField()),
                ('SourceChannel', models.CharField(max_length=255)),
                ('DestinationChannel', models.CharField(max_length=255)),
                ('TransID', models.CharField(max_length=255)),
            ],
        ),
    ]
