# Generated by Django 4.0.4 on 2022-11-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
